name: Build & publish images
on: push

jobs:
  build-and-push-image:
    environment: docker
    runs-on: ubuntu-latest    
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./udagram-api-feed/dockerfile
            image: oyinbayode/udagram-api-feed
          - dockerfile: ./udagram-reverseproxy/dockerfile
            image: oyinbayode/udagram-reverseproxy
          - dockerfile: ./udagram-api-user/dockerfile
            image: oyinbayode/udagram-api-user
          - dockerfile: ./udagram-frontend/dockerfile
            image: oyinbayode/udagram-frontend
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ github.actor }}
          password: 'B@1ya4da2'
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
